import type { TopicSeed } from "./types";

const topic: TopicSeed = {
  slug: "patellofemoral-pain",
  title: "Patellofemoral Pain & Anterior Knee Pain",
  category: "Musculoskeletal",
  description:
    "Understand why the front of the knee hurts with stairs, squats and sitting — and how education, hip and knee strengthening and sensible load management resolve the most common knee complaint in active people.",
  difficulty: "Beginner",
  estMinutes: 26,
  icon: "zap",
  keyTakeaways: [
    "Patellofemoral pain (PFP) is anterior or retropatellar knee pain aggravated by activities that load a flexed knee — squatting, stairs, running, and prolonged sitting.",
    "PFJ compressive load rises steeply with knee flexion: forces reach roughly 3–4× body weight on stairs and 7–8× during deep squatting.",
    "PFP is a diagnosis of exclusion made clinically — no imaging or single special test confirms it.",
    "It is usually a load-tolerance problem, not structural damage: most episodes follow a spike in activity relative to what the knee was conditioned for.",
    "Combined hip AND knee strengthening produces better outcomes than knee strengthening alone.",
    "Education and reassurance are first-line: PFP is common, non-damaging and manageable — fear and rest make it worse.",
    "Patellar tendinopathy is a different diagnosis: localised inferior-pole pain with energy-storage loading (jumping), unlike the diffuse, flexion-load-related pain of PFP.",
    "Taping and foot orthoses can reduce pain short-term in some patients, but only as adjuncts to exercise and load management.",
  ],
  sections: [
    {
      slug: "pfj-mechanics",
      title: "Patellofemoral Joint Mechanics & Load",
      estMinutes: 3,
      content: [
        {
          kind: "paragraph",
          text: "The patella is a sesamoid bone embedded in the quadriceps tendon. It glides in the femoral trochlea, increasing the lever arm of the quadriceps and distributing enormous compressive forces through the thickest articular cartilage in the body. Patellofemoral pain (PFP) is pain arising from this joint and its surrounding tissues, felt at the front of or behind the kneecap.",
        },
        { kind: "image", illustration: "knee-joint", caption: "The patella sits in the femoral trochlea at the front of the knee — compressive load between patella and femur rises steeply as the knee bends under load." },
        {
          kind: "paragraph",
          text: "The crucial mechanical fact is that patellofemoral compressive load increases with both quadriceps force and knee flexion angle. Walking on the flat produces around half body weight of PFJ load; stairs raise it to roughly 3–4× body weight; deep squatting to about 7–8×. This is exactly why stairs, squatting, running (especially downhill) and rising after prolonged sitting are the classic aggravators.",
        },
        {
          kind: "table",
          headers: ["Activity", "Approx. PFJ compressive load"],
          rows: [
            ["Walking (level)", "~0.5× body weight"],
            ["Stair climbing / descending", "~3–4× body weight"],
            ["Running", "~4–6× body weight"],
            ["Deep squatting", "~7–8× body weight"],
          ],
        },
        {
          kind: "keypoints",
          title: "Why the classic aggravators aggravate",
          items: [
            "Stairs and squats: high quadriceps force at large flexion angles = peak PFJ compression",
            "Prolonged sitting (\"movie-goer's sign\" / cinema sign): sustained low-grade compression of a sensitised joint with the knee flexed",
            "Downhill running: large eccentric quadriceps demand each stride",
            "Kneeling: direct pressure over sensitised anterior structures",
          ],
        },
        {
          kind: "pearls",
          items: [
            "Patellofemoral cartilage is aneural — pain is generated by richly innervated structures such as subchondral bone, the fat pad, retinaculum and synovium, usually because load exceeded tolerance, not because something is torn.",
            "The joint tolerates huge loads when conditioned to them — elite weightlifters squat multiples of body weight pain-free.",
          ],
        },
      ],
    },
    {
      slug: "who-and-why",
      title: "Who Gets PFP & Contributing Factors",
      estMinutes: 3,
      difficulty: "Beginner",
      content: [
        {
          kind: "paragraph",
          text: "PFP is one of the most common presentations in musculoskeletal practice. It particularly affects adolescents and young adults, active people (runners, military recruits, court-sport athletes), and is more common in females. It also occurs in less active people after unaccustomed activity — a hiking holiday, a new stair-heavy job, or a January running programme.",
        },
        {
          kind: "cards",
          items: [
            { title: "Load spike", text: "The most consistent trigger: a rapid increase in running distance, hill work, stairs or squatting volume beyond what the knee was conditioned for.", icon: "trending-up" },
            { title: "Quadriceps & hip weakness", text: "Reduced quadriceps and hip abductor/external rotator strength are associated with PFP and are the most treatable factors we know.", icon: "dumbbell" },
            { title: "Movement habits", text: "Dynamic knee valgus (hip adduction and internal rotation on landing/stairs) may concentrate load in some patients — a modifiable pattern, not a structural fault.", icon: "move" },
            { title: "Psychosocial factors", text: "Fear of movement, low mood and catastrophising are common in persistent PFP and predict worse outcomes — address them directly.", icon: "brain" },
          ],
        },
        {
          kind: "paragraph",
          text: "Equally important is what PFP is NOT. It is not \"cartilage wearing out\", the patella is very rarely truly \"maltracking\" in a structural sense, and imaging findings such as chondromalacia correlate poorly with symptoms. Framing PFP as structural doom is inaccurate and drives fear-avoidance; framing it as a fitness/load mismatch is accurate and empowering.",
        },
        {
          kind: "keypoints",
          title: "The load-capacity story",
          items: [
            "Pain starts when applied load exceeds current tissue tolerance — usually after a spike",
            "Weakness, sleep debt and stress all lower tolerance",
            "Treatment raises tolerance (strengthening) while temporarily trimming load — not eliminating it",
            "Structure on imaging rarely explains symptoms in PFP",
          ],
        },
        {
          kind: "pearls",
          items: [
            "Ask \"what changed in the month before this started?\" — a load spike is found in most histories.",
            "Avoid the words \"wear and tear\" and \"maltracking\" with patients — both are usually wrong and both increase fear.",
          ],
        },
      ],
    },
    {
      slug: "assessment",
      title: "Assessment & Diagnosis",
      estMinutes: 3,
      content: [
        {
          kind: "paragraph",
          text: "PFP is a clinical diagnosis of exclusion: anterior or retropatellar pain reproduced by activities that load the flexed patellofemoral joint (squatting, stairs, running, prolonged sitting), once other sources of anterior knee pain have been ruled out. No imaging finding or single special test confirms it, and patellar compression/grind tests are unreliable and can be painful in normal knees.",
        },
        {
          kind: "steps",
          items: [
            { title: "History", text: "Location (diffuse anterior/retropatellar, often described with a hand cupped over the kneecap), aggravators (stairs, squats, sitting, running), training history and the load spike, previous episodes, fears and goals." },
            { title: "Rule out differentials", text: "Screen for localised inferior-pole pain (patellar tendinopathy), instability episodes (patellar dislocation), effusion and trauma (intra-articular pathology), joint-line pain (meniscus/tibiofemoral), and referred hip or lumbar pain — always screen the hip, especially in adolescents." },
            { title: "Functional load tests", text: "Reproduce the pain with squat, step-down or single-leg squat: a painful squat is the most sensitive simple finding. Observe control — pelvic drop, hip adduction, knee valgus, trunk lean." },
            { title: "Strength", text: "Assess quadriceps and hip abduction/external rotation strength (dynamometry or repetition maximum tests such as sit-to-stand and step-down capacity)." },
            { title: "Baseline measures", text: "Pain during a standard task (e.g. step-down NPRS), single-leg squat quality, and a patient-reported measure (e.g. Kujala AKPS) to track progress." },
          ],
        },
        {
          kind: "warning",
          title: "Assessment pitfalls",
          items: [
            "Ordering imaging for typical PFP — findings like chondromalacia are common in pain-free knees and invite nocebo",
            "Diagnosing \"maltracking\" from visual inspection of patellar position — static position correlates poorly with pain",
            "Relying on patellar grind tests — positive in many asymptomatic people",
            "Forgetting the hip: in an adolescent with knee pain, always screen for hip pathology (e.g. slipped upper femoral epiphysis)",
          ],
        },
        {
          kind: "redflags",
          items: [
            "Knee pain in an adolescent with a limp or restricted hip rotation — exclude slipped upper femoral epiphysis (hip pathology refers to the knee)",
            "Significant effusion, trauma, locking or true giving-way — intra-articular pathology, not PFP",
            "Night pain, fever, weight loss, or a history of malignancy",
            "Hot, swollen, red joint — infection or inflammatory arthritis",
          ],
        },
      ],
    },
    {
      slug: "differentials",
      title: "Differential Diagnosis",
      estMinutes: 2,
      difficulty: "Intermediate",
      content: [
        {
          kind: "paragraph",
          text: "The most important — and most commonly confused — differential is patellar tendinopathy, because the two conditions share a postcode but need different loading programmes.",
        },
        {
          kind: "table",
          headers: ["Feature", "Patellofemoral pain", "Patellar tendinopathy"],
          rows: [
            ["Pain location", "Diffuse anterior/retropatellar — patient cups the kneecap", "Pinpoint at the inferior pole of the patella — patient points with one finger"],
            ["Classic aggravators", "Stairs, squatting, prolonged sitting, running", "Jumping, landing, change of direction — energy-storage loading"],
            ["Typical person", "Broad: adolescents, runners, less active people after load spikes; more females", "Jumping athletes (volleyball, basketball); more males"],
            ["Pain behaviour", "Varies with PFJ compressive load", "Dose-dependent with tendon energy-storage load; often warms up during activity"],
            ["Key management difference", "Hip + knee strengthening across comfortable ranges", "Progressive tendon loading (isometrics → heavy slow resistance → energy storage)"],
          ],
        },
        {
          kind: "cards",
          items: [
            { title: "Fat pad irritation", text: "Sharp inferior-anterior pain, aggravated by knee extension/hyperextension and direct pressure; often follows a knock or overzealous taping.", icon: "alert-circle" },
            { title: "Patellofemoral OA", text: "Older patients with anterior knee pain on stairs, crepitus and stiffness — same load principles, longer timeframes.", icon: "clock" },
            { title: "Patellar instability", text: "Episodes of the kneecap slipping or dislocating, apprehension on lateral patellar glide — a different pathway with different priorities.", icon: "alert-triangle" },
            { title: "Referred pain", text: "Hip pathology and lumbar referral can both present as anterior knee pain — screen proximally, especially in adolescents.", icon: "arrow-up" },
          ],
        },
        {
          kind: "pearls",
          items: [
            "One finger on the inferior pole = think tendon; a whole hand over the kneecap = think PFJ.",
            "Osgood-Schlatter (tibial tuberosity) and Sinding-Larsen-Johansson (inferior pole) are the adolescent traction apophysitis variants of anterior knee pain — manage with load modification, not rest until skeletal maturity.",
          ],
        },
      ],
    },
    {
      slug: "education-first-line",
      title: "Education: The First-Line Treatment",
      estMinutes: 2,
      difficulty: "Beginner",
      content: [
        {
          kind: "paragraph",
          text: "International consensus statements on PFP place education at the centre of treatment. What patients believe determines what they do: if they believe their kneecap is wearing out, they rest, weaken and worsen; if they understand the load-capacity story, they engage with strengthening and graded activity.",
        },
        {
          kind: "cards",
          items: [
            { title: "Explain the diagnosis", text: "\"The joint behind your kneecap is sensitised because load recently exceeded what it was conditioned for — nothing is damaged or wearing out.\"", icon: "message-circle" },
            { title: "Set expectations", text: "Recovery is usually weeks to months, not days. Strength changes take 6–12 weeks. Flare-ups along the way are normal and manageable.", icon: "calendar" },
            { title: "Keep moving", text: "Complete rest lowers tolerance further. Modify — reduce hills, trim volume, break up sitting — rather than stop.", icon: "activity" },
            { title: "Self-management", text: "Teach the 24-hour rule (pain up to ~3–5/10 that settles by next morning is acceptable) so patients can self-dose activity confidently.", icon: "shield" },
          ],
        },
        {
          kind: "pearls",
          items: [
            "Education alone outperforms many passive treatments in trials — it is a treatment, not an add-on.",
            "Replace \"my kneecap doesn't track properly\" with \"my knee is under-conditioned for what I asked of it\" — same patient, opposite behaviour.",
          ],
        },
      ],
    },
    {
      slug: "exercise-therapy",
      title: "Exercise Therapy: Hip + Knee",
      estMinutes: 3,
      content: [
        {
          kind: "paragraph",
          text: "Exercise therapy is the best-evidenced treatment for PFP. Systematic reviews and consensus statements consistently recommend combining hip-targeted exercise (abductors, extensors, external rotators) with knee-targeted (quadriceps) exercise — the combination beats either alone for pain and function in the medium and long term.",
        },
        { kind: "image", illustration: "resistance-band", caption: "A simple resistance band supports most of the hip-targeted programme — abduction, external rotation and bridging variations — at home with progressive resistance." },
        {
          kind: "steps",
          items: [
            { title: "Start where it doesn't flare", text: "Choose loads and ranges that keep pain ≤3–5/10 and settled by next morning. Smaller flexion angles (0–45°) keep PFJ stress lower in loaded exercises early on." },
            { title: "Load the hip", text: "Side-lying/standing abduction, banded external rotation, side-planks, hip thrusts — hip work is often less provocative early, so it can carry the load while the knee settles." },
            { title: "Load the quadriceps", text: "Leg press or squats through comfortable range, step-downs, seated knee extension in tolerable ranges. The quadriceps must eventually be loaded — avoiding them is a common reason for failure." },
            { title: "Progress to function", text: "Single-leg squats, step-downs from increasing heights, lunges, landing control — build toward the tasks the patient actually needs." },
            { title: "Persist 6–12+ weeks", text: "Strength adaptation is slow; most trials showing benefit run at least 6 weeks and improvement continues well beyond." },
          ],
        },
        {
          kind: "keypoints",
          title: "PFJ-friendly early loading",
          items: [
            "Loaded knee flexion 0–45° (squats, leg press) keeps PFJ stress relatively low — deep ranges come later",
            "Open-chain knee extension loads the PFJ most in the last 30° toward full extension under heavy load — start with mid-range and moderate loads if provocative, and reintroduce ranges progressively",
            "Pain up to ~3–5/10 during exercise, settling within 24 h, is acceptable and safe",
            "Progress one variable at a time: range, then load, then speed/impact",
          ],
        },
        {
          kind: "pearls",
          items: [
            "If every knee exercise flares the pain, spend two weeks on hip-dominant work and isometrics, then reintroduce knee loading — capacity built proximally buys tolerance distally.",
            "Strength gains often precede pain reduction by weeks — warn patients so they don't quit at week three.",
          ],
        },
      ],
    },
    {
      slug: "load-management",
      title: "Load Management & Return to Running",
      estMinutes: 2,
      content: [
        {
          kind: "paragraph",
          text: "Because most PFP follows a load spike, management always includes trimming the provocative load to a tolerable level — then rebuilding it gradually. For runners this means manipulating distance, frequency, hills and cadence rather than stopping altogether whenever possible.",
        },
        {
          kind: "steps",
          items: [
            { title: "Find the tolerable dose", text: "Reduce volume (often by ~50%), flatten the route, and split long runs. Symptoms ≤3–5/10 during and settled by next morning define the acceptable dose." },
            { title: "Modify mechanics if needed", text: "Increasing step rate (cadence) by 5–10% reduces PFJ load per stride and can allow running to continue during rehab." },
            { title: "Rebuild gradually", text: "Increase weekly volume conservatively (commonly ~10% per week as a guide), adding hills and speed last. One variable at a time." },
            { title: "Monitor and adjust", text: "Use a simple diary of dose and 24-hour response. A flare means the last increase was too big — step back one level, not to zero." },
          ],
        },
        {
          kind: "warning",
          title: "Load management mistakes",
          items: [
            "Complete rest until pain-free — tolerance drops and pain returns at even lower loads",
            "Boom-and-bust: doubling the load on a good week, then flaring and resting",
            "Changing everything at once (shoes, cadence, volume, strength work) so nothing can be evaluated",
            "Ignoring sitting time — for desk-based patients, breaking up prolonged sitting matters as much as running dose",
          ],
        },
      ],
    },
    {
      slug: "adjuncts",
      title: "Taping, Orthoses & Other Adjuncts",
      estMinutes: 2,
      content: [
        {
          kind: "paragraph",
          text: "Several adjuncts can reduce pain in the short term, creating a window in which exercise is more comfortable. None fix PFP on their own, and consensus guidance is explicit that they should be combined with — never substituted for — exercise and load management.",
        },
        {
          kind: "cards",
          items: [
            { title: "Patellar taping", text: "Tailored (e.g. McConnell-style medial glide) taping can reduce pain immediately in some patients — useful to enable exercise early. Effects are short-term.", icon: "bandage" },
            { title: "Foot orthoses", text: "Prefabricated orthoses may help short-term pain in a subgroup (often those with greater pronation) — evidence supports short-term use, not routine prescription for all.", icon: "footprints" },
            { title: "Manual therapy & stretching", text: "May provide short-term comfort as part of a package; neither changes outcomes alone. Calf, hamstring and quadriceps flexibility work is reasonable when deficits exist.", icon: "hand" },
            { title: "What NOT to rely on", text: "Electrotherapy, knee braces as primary treatment, and routine imaging-driven interventions have no meaningful support in PFP.", icon: "x-circle" },
          ],
        },
        {
          kind: "pearls",
          items: [
            "A good screening question for taping: does the patient's step-down pain drop meaningfully with tape applied? If yes, use it as a bridge into loading.",
            "Surgery has essentially no role in routine PFP.",
          ],
        },
      ],
    },
    {
      slug: "exercise-blocks",
      title: "Key Exercises",
      estMinutes: 4,
      content: [
        {
          kind: "paragraph",
          text: "A representative PFP programme: quadriceps loading in a PFJ-friendly range, a functional eccentric control exercise, and hip-targeted work. Progress each over 6–12 weeks using the 24-hour rule.",
        },
        {
          kind: "exercise",
          name: "Leg press (range-limited)",
          purpose: "Build quadriceps strength while keeping patellofemoral stress manageable.",
          position: "Seated on the leg press, feet hip-width on the platform.",
          execution: "Lower under control to about 45–60° of knee flexion, then press back out without locking the knees harshly.",
          dosage: "8–12 reps × 3 sets, 2–3×/week, at a load where the last reps feel hard (~7–8/10 effort).",
          progression: "Increase load first, then gradually deepen range toward 90° as tolerance improves; progress toward single-leg.",
          precautions: "Keep pain ≤3–5/10 and settled by next morning; deepen range before adding speed.",
        },
        {
          kind: "exercise",
          name: "Step-downs",
          purpose: "Eccentric quadriceps control in the exact task (stairs) most patients struggle with; retrains hip-knee alignment.",
          position: "Standing on a low step (start 10 cm), hands free or light fingertip support.",
          execution: "Slowly lower the free heel toward the floor over 2–3 seconds, keeping the pelvis level and the knee tracking over the foot, tap the heel and return.",
          dosage: "8–12 reps each side × 2–3 sets, 3×/week.",
          progression: "Increase step height, add a slow tempo, hold a dumbbell, or remove support.",
          precautions: "Quality first: no pelvic drop or knee collapse inward. Reduce height if pain exceeds the acceptable range.",
        },
        {
          kind: "exercise",
          name: "Side-plank with hip abduction",
          purpose: "High-level gluteus medius and lateral trunk strengthening — hip-targeted work with strong evidence in PFP.",
          position: "Side-lying propped on the forearm, knees or feet stacked (knees = easier version).",
          execution: "Lift the pelvis into a straight line, then raise the top leg 20–30 cm, lower it, and keep the pelvis from sagging.",
          dosage: "6–10 leg lifts × 2–3 sets per side, 3×/week.",
          progression: "From knees to feet, add holds, or add a band around the thighs.",
          precautions: "Keep the body in one line; shoulder discomfort means re-set the elbow under the shoulder.",
        },
        {
          kind: "exercise",
          name: "Glute bridge",
          purpose: "Hip extensor strengthening with minimal patellofemoral load — ideal early or during flares.",
          position: "Supine, knees bent, feet hip-width.",
          execution: "Squeeze the glutes and lift the pelvis to a straight line from shoulders to knees; hold 3 seconds; lower slowly.",
          dosage: "10–15 reps × 2–3 sets, daily to alternate days.",
          progression: "Single-leg bridge, feet elevated, band above the knees, or barbell hip thrust in the gym.",
          precautions: "Push through the heels; avoid arching the lower back at the top.",
        },
        {
          kind: "keypoints",
          title: "Programme logic",
          items: [
            "Hip work carries load early when the knee is irritable; quadriceps work is progressively reintroduced — both are essential",
            "The step-down doubles as an outcome measure: height + reps + pain score tracked weekly",
            "Expect 6–12 weeks for meaningful strength change — set the expectation at session one",
          ],
        },
      ],
    },
    {
      slug: "quick-revision",
      title: "Quick Revision Summary",
      estMinutes: 2,
      difficulty: "Beginner",
      content: [
        {
          kind: "keypoints",
          title: "60-second summary",
          items: [
            "PFP = diffuse anterior/retropatellar pain with loaded knee flexion: stairs, squats, running, prolonged sitting",
            "PFJ load: ~0.5× body weight walking, 3–4× stairs, 7–8× deep squat — a load-tolerance problem, not structural doom",
            "Diagnosis of exclusion: clinical, no imaging needed; squat/step-down reproduce pain; screen the hip (adolescents!)",
            "Tendon vs PFP: one finger on the inferior pole + jumping pain = patellar tendinopathy",
            "Treatment: education + hip AND knee strengthening + load management, 6–12+ weeks",
            "Runners: trim volume, flatten hills, consider +5–10% cadence, rebuild ~10%/week",
            "Tape and orthoses are short-term adjuncts only; surgery has essentially no role",
            "Red flags: adolescent limp with restricted hip rotation (SUFE), effusion/trauma/locking, night pain and systemic features",
          ],
        },
        {
          kind: "paragraph",
          text: "Ready to test yourself? Take the quiz to check your understanding and find your weak areas.",
        },
      ],
    },
  ],
  questions: [
    {
      text: "Which set of activities classically aggravates patellofemoral pain?",
      options: [
        "Walking on flat ground and lying down",
        "Stairs, squatting, running and prolonged sitting",
        "Jumping and landing only",
        "Wrist extension and gripping",
      ],
      correctIndex: 1,
      explanation:
        "PFP is aggravated by activities that compress the patellofemoral joint with the knee flexed under quadriceps load — stairs, squatting and running — plus prolonged sitting (the \"cinema sign\"), which sustains low-grade compression on a sensitised joint.",
      difficulty: "Easy",
      tags: ["assessment", "pathology"],
      sectionSlug: "pfj-mechanics",
    },
    {
      text: "Approximately how much patellofemoral compressive load is produced during stair climbing compared with level walking?",
      options: [
        "About the same — roughly 0.5× body weight for both",
        "Stairs ~3–4× body weight versus ~0.5× for level walking",
        "Stairs produce less load than walking",
        "Both exceed 10× body weight",
      ],
      correctIndex: 1,
      explanation:
        "PFJ compression rises steeply with knee flexion angle and quadriceps force: roughly 0.5× body weight during level walking, 3–4× on stairs and 7–8× in deep squatting — which is precisely why stairs and squats are the hallmark aggravators.",
      difficulty: "Medium",
      tags: ["anatomy", "pathology"],
      sectionSlug: "pfj-mechanics",
    },
    {
      text: "How is patellofemoral pain diagnosed?",
      options: [
        "MRI showing chondromalacia patellae",
        "A positive patellar grind test",
        "Clinically, as a diagnosis of exclusion — anterior/retropatellar pain with loaded knee flexion once other causes are ruled out",
        "X-ray showing lateral patellar tilt",
      ],
      correctIndex: 2,
      explanation:
        "No imaging finding or single special test confirms PFP. It is diagnosed clinically from the pattern — anterior or retropatellar pain reproduced by squatting, stairs, running or prolonged sitting — after excluding differentials. Chondromalacia and patellar tilt are common in pain-free knees, and grind tests are positive in many asymptomatic people.",
      difficulty: "Easy",
      tags: ["assessment", "clinical-reasoning"],
      sectionSlug: "assessment",
    },
    {
      text: "A volleyball player has pinpoint pain at the inferior pole of the patella, worst with jumping and landing. What is the most likely diagnosis?",
      options: ["Patellofemoral pain", "Patellar tendinopathy", "Fat pad irritation", "Pes anserine bursitis"],
      correctIndex: 1,
      explanation:
        "Localised, one-finger pain at the inferior pole provoked by energy-storage loading (jumping, landing, change of direction) in a jumping athlete is the classic picture of patellar tendinopathy. PFP is more diffuse and driven by compressive flexion loading such as stairs and sitting; the two need different loading programmes.",
      difficulty: "Easy",
      tags: ["clinical-reasoning", "assessment"],
      sectionSlug: "differentials",
    },
    {
      text: "Which exercise approach has the best evidence for patellofemoral pain?",
      options: [
        "Quadriceps strengthening alone",
        "Hip strengthening alone",
        "Combined hip AND knee (quadriceps) strengthening",
        "Stretching only, with no resistance work",
      ],
      correctIndex: 2,
      explanation:
        "Systematic reviews and international consensus statements consistently recommend combining hip-targeted exercise (abductors, extensors, external rotators) with quadriceps strengthening — the combination produces better pain and function outcomes than either component alone.",
      difficulty: "Easy",
      tags: ["exercise-therapy", "management"],
      sectionSlug: "exercise-therapy",
    },
    {
      text: "Why are hip-dominant exercises particularly useful EARLY in PFP rehabilitation?",
      options: [
        "They directly regrow patellar cartilage",
        "They load the kinetic chain and build capacity while producing little patellofemoral compression",
        "They permanently correct patellar tracking",
        "They replace the need for any quadriceps work",
      ],
      correctIndex: 1,
      explanation:
        "Bridges, abduction and side-plank work strengthen the hip with minimal PFJ compression, so they can carry training load while the irritable joint settles. Quadriceps loading must still be reintroduced progressively — avoiding it altogether is a common reason programmes fail.",
      difficulty: "Medium",
      tags: ["exercise-therapy", "clinical-reasoning"],
      sectionSlug: "exercise-therapy",
    },
    {
      text: "A runner with PFP wants to keep running during rehabilitation. Which modification is best supported?",
      options: [
        "Stop running completely until pain-free for a month",
        "Reduce volume, flatten the route, and consider increasing cadence by 5–10% to lower PFJ load per stride",
        "Double the weekly distance to build tolerance faster",
        "Switch all runs to downhill routes",
      ],
      correctIndex: 1,
      explanation:
        "Load management means trimming to a tolerable dose, not stopping: reduce volume, remove hills, split runs, and consider a 5–10% cadence increase, which reduces patellofemoral load per stride. Complete rest lowers tolerance; downhill running increases eccentric quadriceps demand and PFJ load.",
      difficulty: "Medium",
      tags: ["management", "exercise-therapy"],
      sectionSlug: "load-management",
    },
    {
      text: "Which statement about imaging in PFP is correct?",
      options: [
        "Chondromalacia on MRI confirms the diagnosis",
        "Imaging findings correlate poorly with symptoms and routine imaging is not indicated",
        "X-ray is required before starting exercise",
        "A normal MRI excludes patellofemoral pain",
      ],
      correctIndex: 1,
      explanation:
        "Findings such as chondromalacia and patellar tilt are common in pain-free knees, correlate poorly with symptoms, and can create nocebic beliefs. PFP is a clinical diagnosis; imaging is reserved for atypical features, trauma or red flags.",
      difficulty: "Medium",
      tags: ["assessment", "clinical-reasoning"],
      sectionSlug: "assessment",
    },
    {
      text: "An adolescent presents with anterior knee pain, a limp, and markedly restricted hip internal rotation. What must be excluded first?",
      options: [
        "Patellar tendinopathy",
        "Slipped upper femoral epiphysis (hip pathology referring to the knee)",
        "Simple growing pains",
        "Iliotibial band syndrome",
      ],
      correctIndex: 1,
      explanation:
        "Hip pathology refers pain to the knee, and in adolescents a slipped upper femoral epiphysis (SUFE) classically presents as knee or thigh pain with a limp and restricted hip internal rotation. Missing it risks avascular necrosis — the hip must be examined in every young person with knee pain.",
      difficulty: "Hard",
      tags: ["clinical-reasoning", "precautions"],
      sectionSlug: "assessment",
    },
    {
      text: "What is the most consistent trigger identified in the history of a new episode of PFP?",
      options: [
        "A recent spike in activity load relative to what the knee was conditioned for",
        "A specific traumatic patellar dislocation",
        "Wearing new glasses",
        "A high-protein diet",
      ],
      correctIndex: 0,
      explanation:
        "Most episodes of PFP follow a rapid increase in flexion-loading activity — more running, hills, stairs or squats than the joint was conditioned for. Asking \"what changed in the month before this started?\" usually uncovers the spike, and correcting it is central to treatment.",
      difficulty: "Easy",
      tags: ["pathology", "clinical-reasoning"],
      sectionSlug: "who-and-why",
    },
    {
      text: "Which explanation of PFP to a patient is both accurate and helpful?",
      options: [
        "\"Your kneecap is off track and grinding away your cartilage\"",
        "\"The joint is sensitised because load exceeded its current tolerance — nothing is damaged, and strengthening will raise that tolerance\"",
        "\"You have early arthritis and should avoid stairs permanently\"",
        "\"The pain is imaginary\"",
      ],
      correctIndex: 1,
      explanation:
        "The load-capacity explanation is accurate (structural findings correlate poorly with symptoms) and drives helpful behaviour: engagement with strengthening and graded activity. \"Maltracking\" and \"wear\" narratives are usually inaccurate and increase fear-avoidance, which worsens outcomes.",
      difficulty: "Easy",
      tags: ["management", "clinical-reasoning"],
      sectionSlug: "education-first-line",
    },
    {
      text: "During loaded squatting exercise for PFP, which range keeps patellofemoral stress relatively low in early rehabilitation?",
      options: ["0–45° of knee flexion", "90–120° of knee flexion", "Full deep squat range", "Range is irrelevant to PFJ stress"],
      correctIndex: 0,
      explanation:
        "PFJ compressive stress in closed-chain (loaded) exercises rises with flexion depth, so limiting squats and leg press to roughly 0–45° (progressing toward 60–90° as tolerance builds) keeps early loading comfortable. Deep ranges are reintroduced progressively, not avoided forever.",
      difficulty: "Medium",
      tags: ["exercise-therapy", "anatomy"],
      sectionSlug: "exercise-therapy",
    },
    {
      text: "Which statement about patellar taping and foot orthoses in PFP reflects the evidence?",
      options: [
        "They are the definitive treatment and replace exercise",
        "They can reduce pain short-term in some patients and are useful adjuncts to enable exercise",
        "They are harmful and should never be used",
        "Orthoses work for everyone regardless of foot posture",
      ],
      correctIndex: 1,
      explanation:
        "Tailored taping and prefabricated orthoses can produce short-term pain reduction in subgroups of patients — valuable as a bridge into loading — but neither changes long-term outcomes alone. Consensus guidance combines them with exercise and load management, never instead of it.",
      difficulty: "Medium",
      tags: ["management", "clinical-reasoning"],
      sectionSlug: "adjuncts",
    },
    {
      text: "A patient reports 4/10 anterior knee pain during step-downs, settling fully by the next morning. What should you advise?",
      options: [
        "Stop the exercise — pain means the exercise is causing damage",
        "Continue — this response is within the acceptable range and indicates appropriate loading",
        "Switch permanently to stretching",
        "Only exercise once symptoms are 0/10 at all times",
      ],
      correctIndex: 1,
      explanation:
        "Widely used symptom-monitoring guidance for PFP accepts pain up to about 3–5/10 during exercise provided it settles to baseline within 24 hours. This response indicates adaptive loading; the programme can continue and progress. Waiting for zero pain leads to deconditioning.",
      difficulty: "Medium",
      tags: ["exercise-therapy", "clinical-reasoning"],
      sectionSlug: "exercise-blocks",
    },
    {
      text: "Sharp anterior knee pain just below the patella that is worse in full knee EXTENSION and with direct pressure most suggests which differential?",
      options: ["Patellofemoral pain", "Infrapatellar fat pad irritation", "Medial meniscal tear", "Quadriceps tendinopathy"],
      correctIndex: 1,
      explanation:
        "The infrapatellar fat pad is highly innervated and is pinched in end-range extension/hyperextension — the opposite pattern to PFP, which is provoked by loaded flexion. Fat pad irritation often follows a direct knock or overly aggressive inferior taping and is exquisitely tender to direct palpation.",
      difficulty: "Hard",
      tags: ["clinical-reasoning", "assessment"],
      sectionSlug: "differentials",
    },
    {
      text: "In which part of range does heavily loaded open-chain knee extension stress the patellofemoral joint most?",
      options: [
        "The last 30° approaching full extension under load",
        "Deep flexion beyond 120°",
        "It is identical across all ranges",
        "Open-chain extension produces no PFJ load",
      ],
      correctIndex: 0,
      explanation:
        "In open-chain knee extension the external lever arm — and quadriceps demand per unit of contact area — is greatest approaching terminal extension, so heavily loaded end-range open-chain work is often provocative in irritable PFP. Starting with mid-range, moderate loads and progressively restoring ranges is the practical approach (contrast with closed chain, where stress rises with flexion depth).",
      difficulty: "Hard",
      tags: ["exercise-therapy", "anatomy"],
      sectionSlug: "exercise-therapy",
    },
    {
      text: "Which combination of findings would make you doubt a diagnosis of PFP and investigate further?",
      options: [
        "Diffuse anterior pain on stairs with a painful single-leg squat",
        "Pain after prolonged sitting that eases with movement",
        "A tense effusion, mechanical locking, and a history of significant trauma",
        "Pain of 3/10 during step-downs settling overnight",
      ],
      correctIndex: 2,
      explanation:
        "Effusion, true locking and significant trauma point to intra-articular pathology (meniscal tear, osteochondral injury, ligament rupture) rather than PFP, which produces little or no swelling. The other options are all typical PFP behaviour.",
      difficulty: "Hard",
      tags: ["clinical-reasoning", "precautions"],
      sectionSlug: "assessment",
    },
    {
      text: "Why do consensus statements warn against complete rest as a treatment for PFP?",
      options: [
        "Rest is expensive",
        "Unloading lowers tissue tolerance further, so pain typically returns at even lower loads",
        "Rest causes immediate patellar dislocation",
        "Rest only works in adolescents",
      ],
      correctIndex: 1,
      explanation:
        "PFP is a load-tolerance problem. Complete rest deconditions the quadriceps, hip and joint tissues, lowering the load threshold at which symptoms appear — the classic pattern of feeling better with rest then flaring immediately on return. Modified, graded loading maintains capacity while sensitivity settles.",
      difficulty: "Medium",
      tags: ["management", "pathology"],
      sectionSlug: "education-first-line",
    },
    {
      text: "A patient's step-down pain drops from 5/10 to 1/10 immediately after patellar taping is applied. How should this finding be used?",
      options: [
        "Tape indefinitely as the definitive treatment",
        "Use taping as a short-term adjunct that enables more comfortable loading while the exercise programme builds capacity",
        "Conclude the diagnosis must be wrong",
        "Abandon exercise since tape alone solved the problem",
      ],
      correctIndex: 1,
      explanation:
        "An immediate meaningful pain reduction with tape identifies a patient likely to benefit from taping — as a bridge. The effect is short-lived and does not change long-term outcomes, so it is used to make early loading comfortable while hip and knee strengthening does the durable work over 6–12+ weeks.",
      difficulty: "Hard",
      tags: ["management", "clinical-reasoning"],
      sectionSlug: "adjuncts",
    },
  ],
  flashcards: [
    { front: "Define patellofemoral pain (PFP).", back: "Diffuse anterior or retropatellar knee pain aggravated by activities loading a flexed knee — squatting, stairs, running, prolonged sitting. A clinical diagnosis of exclusion." },
    { front: "Approximate PFJ loads: walking, stairs, deep squat?", back: "~0.5× body weight walking, ~3–4× on stairs, ~7–8× in deep squatting." },
    { front: "What is the \"cinema sign\"?", back: "Anterior knee pain after prolonged sitting with flexed knees — sustained low-grade PFJ compression on a sensitised joint. Classic for PFP." },
    { front: "PFP vs patellar tendinopathy — location and load?", back: "PFP: diffuse pain (hand cupped over patella), flexion-compression loading. Tendinopathy: pinpoint inferior-pole pain, energy-storage loading (jumping/landing)." },
    { front: "Best-evidenced exercise approach for PFP?", back: "Combined hip (abductors, extensors, external rotators) AND knee (quadriceps) strengthening — better than either alone, over 6–12+ weeks." },
    { front: "Acceptable pain rule during PFP rehab?", back: "Pain up to ~3–5/10 during exercise that settles to baseline within 24 hours indicates acceptable loading." },
    { front: "Running modifications for PFP?", back: "Trim volume (~50%), flatten hills, split runs, consider increasing cadence 5–10% to cut PFJ load per stride; rebuild ~10% per week." },
    { front: "Role of taping and foot orthoses in PFP?", back: "Short-term pain-reducing adjuncts in some patients — used to enable exercise, never instead of it." },
    { front: "PFJ-friendly early loading ranges?", back: "Closed-chain (squat/leg press) 0–45° flexion keeps stress low early; heavily loaded open-chain extension is most provocative approaching terminal extension." },
    { front: "Key red flag in an adolescent with knee pain?", back: "Limp with restricted hip internal rotation — exclude slipped upper femoral epiphysis (SUFE); hip pathology refers to the knee." },
    { front: "Why is complete rest counterproductive in PFP?", back: "It lowers load tolerance further through deconditioning, so pain returns at even smaller loads — modify and grade load instead." },
    { front: "Most consistent trigger for a new PFP episode?", back: "A recent spike in flexion-loading activity (running volume, hills, stairs, squats) beyond current conditioning." },
  ],
};

export default topic;
